---
- name: Configure server
  hosts: all
  become: yes
  vars:
    sysadmin_user: sysadmin
    sysadmin_password: password  # Change password as appropriate
    new_hostname: newhostname   # Change hostname as appropriate
    dns_server: 8.8.8.8         # Change DNS server as appropriate
    log_file: /var/log/command.log  # Log file to store commands

  tasks:
    - name: Update and install initial tools
      apt:
        update_cache: yes
        name: 
          - curl
          - wget
          - vim
          - git
          - net-tools
        state: present

    - name: Change hostname
      hostname:
        name: "{{ new_hostname }}"

    - name: Update /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1'
        line: "127.0.0.1   {{ new_hostname }}"

    - name: Configure DNS server
      lineinfile:
        path: /etc/resolv.conf
        line: "nameserver {{ dns_server }}"
        create: yes

    - name: Set timezone to Vietnam
      timezone:
        name: Asia/Ho_Chi_Minh

    - name: Create sysadmin user
      user:
        name: "{{ sysadmin_user }}"
        password: "{{ sysadmin_password | password_hash('sha512') }}"
        shell: /bin/bash
        groups: sudo
        state: present
        create_home: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start and enable Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Configure Docker daemon
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "10m",
              "max-file": "3"
            },
            "storage-driver": "overlay2"
          }
      notify: Restart Docker

    - name: Optimize TCP/IP settings
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
      with_items:
        - { name: 'net.core.somaxconn', value: '1024' }
        - { name: 'net.core.netdev_max_backlog', value: '5000' }
        - { name: 'net.ipv4.ttcp_max_syn_backlog', value: '4096' }
        - { name: 'net.ipv4.tcp_tw_reuse', value: '1' }
        - { name: 'net.ipv4.tcp_fin_timeout', value: '15' }
        - { name: 'net.ipv4.tcp_keepalive_time', value: '300' }
        - { name: 'net.ipv4.ip_local_port_range', value: '1024 65535' }
        - { name: 'net.ipv4.tcp_syncookies', value: '1' }

    - name: Increase file descriptors limit
      lineinfile:
        path: /etc/security/limits.conf
        line: "{{ item }}"
      with_items:
        - '* soft nofile 100000'
        - '* hard nofile 100000'

    - name: Optimize kernel parameters
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
      with_items:
        - { name: 'vm.swappiness', value: '10' }
        - { name: 'vm.dirty_ratio', value: '15' }
        - { name: 'vm.dirty_background_ratio', value: '5' }

    - name: Enable command logging for all users
      lineinfile:
        path: /etc/profile
        line: |
          # Log all user commands
          export PROMPT_COMMAND='history -a'
          export HISTTIMEFORMAT="%d/%m/%y %T "
          export HISTFILESIZE=50000
          export HISTSIZE=50000
          shopt -s histappend
          function log_command {
            if [[ $(whoami) != "root" ]]; then
              logger -p local1.notice -t bash -i -- "COMMAND: $(history 1 | sed 's/^ *[0-9]* *//')"
            fi
          }
          PROMPT_COMMAND="log_command; $PROMPT_COMMAND"
        create: yes

    - name: Setup syslog to log commands to specific file
      lineinfile:
        path: /etc/rsyslog.d/50-default.conf
        line: "local1.*                        {{ log_file }}"
        create: yes
      notify: Restart rsyslog

  handlers:
    - name: Restart Docker
      systemd:
        name: docker
        state: restarted

    - name: Restart rsyslog
      systemd:
        name: rsyslog
        state: restarted
